site_name: Flight Laboratory
site_url: https://LLKE.github.io/flight-laboratory
repo_url: https://github.com/LLKE/flight-laboratory

theme: 
  name: readthedocs

plugins:
- search
- mkdoxy:
    projects:
      FlightLaboratory:
        src-dirs: "../src"
        full-doc: True
        doxy-cfg:
          FILE_PATTERNS: "*.cpp *.h"
          RECURSIVE: True

nav: 
  - Home: index.md
  - Getting Started: getting-started.md
  - Developer Guide: development.md
  - Architecture: architecture.md
  - Components: components.md
  
